### ISSUE TITLE
Core Helm Feature

### ISSUE THREAD

**Issue by stevehipwell** [bacongobbler/helm-whatup#21]
Is there a reason why this isn't a core Helm feature?

**Comment by bacongobbler** [comment]
Plugins are a good test bed for new features before proposing them as a core feature. Long ago, the scope and use case for a feature like `helm whatup` was undefined. It was better to iterate upon the use case as a plugin before making this a core feature of helm.

Given the amount of community engagement and usage on this plugin over the past few years since initially written, the use case for `helm whatup` is quite niche. The plugin was introduced nearly two years ago and hasn't seen much uptake in the community since then.

**Comment by stevehipwell** [comment]
@bacongobbler - I agree in principal with the plugin as a test bed for new features however in this case I have a couple of observations that I'd be interested in you thoughts on? BTW I think this plugin is great and use it extensively in my workflow.

Observation 1: I'd assume in general that an **outdated** command would be a core competency of a package manager. Furthermore with the command as part of the core product it would be possible to evolve the capability to support real pain points, such as notifying users when a chart has been flagged as outdated and moved to a new repo.

Observation 2: I'm not sure if the metrics on `helm whatup` are valid as an indicator of the demand for an outdated command. I remember being disappointed by the lack of a helm outdated command and it taking me quite a while to find `helm whatup`. As with most plugins this still doesn't work on a Windows machine out of the box (without resorting to WSL) so for a number of users in the corporate world this isn't a working solution.

**Comment by bacongobbler** [comment]
> As with most plugins this still doesn't work on a Windows machine out of the box (without resorting to WSL)

This is something that has to be addressed upstream via https://github.com/helm/helm/issues/7117. Once that work has been implemented by the community, we can look into supporting Windows.

As for the original ask, proposing this plugin as a core feature is not something I am interested in moving forward. `helm whatup` is a niche use case, and is meant to serve as an assistive tool for a small subset of users rather than a tool for the 1M+ monthly users of Helm. For that reason, this will continue to work as a Helm plugin.

Thanks for your feedback.

**Comment by bacongobbler** [comment]
> I remember being disappointed by the lack of a helm outdated command and it taking me quite a while to find `helm whatup`

I recall there being a discussion upstream about implementing `helm search plugin`. If there isn't a ticket available for that feature request, feel free to propose it! I know there has been some level of interest in that topic upstream.

**Comment by stevehipwell** [comment]
@bacongobbler this is quite possibly a stupid question but what is the intended Helm flow for update discovery? I think this is even more relevent with the decentralisation of charts, although any solution would only have the configured repos as source.

**Comment by bacongobbler** [comment]
`helm dependency update`. Same as you would with any other package manager.

**Comment by stevehipwell** [comment]
I don't think I've explained the issue correctly. I'm looking for the Helm equivalent of `apt list --upgradeable` or `yum check-update`. The specific scenario is using Flux to manage cluster configuration and being able to monitor updates and review them.
